In [69]:
import numpy as np
import pandas as pd

In [70]:
df=pd.read_csv("cars.csv")

In [71]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [72]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## Onehotencoding using pandas

In [73]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## k-1 OneHotEncoding

In [74]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [75]:
# we dont use this usaually cos pd doesnt remeber the oclumn nos so we use sckit

## OHE using Sklearn

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=12)

In [77]:
X_test.head()

           brand  km_driven    fuel         owner
7094     Hyundai      19600  Diesel   First Owner
4253  Mitsubishi     100000  Diesel   Third Owner
5427   Chevrolet      90000  Diesel  Second Owner
4203       Honda      28000  Petrol   First Owner
120       Nissan      70000  Diesel   Third Owner

In [78]:
from sklearn.preprocessing import OneHotEncoder
# problem is alag alag cols me jakke implement then merge lenghty so use col transformer

ohe=OneHotEncoder(drop='first')  #ohe=OneHotEncoder(drop='first',sparse=True) => to array krne ak no need

In [79]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [80]:
X_test_new=ohe.fit_transform(X_test[['fuel','owner']]).toarray()

In [81]:
X_train_new#numpy array me convert ho chuaka h

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(6502, 9))

In [82]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape #

(6502, 11)

## OHE with top categories

In [83]:
counts=df['brand'].value_counts()

In [84]:
df['brand'].nunique()
threshold=100

In [86]:
repl=counts[counts <=threshold].index

In [89]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1997,False,False,False,False,False,True,False,False,False,False,False,False,False
5993,False,False,False,False,True,False,False,False,False,False,False,False,False
5390,False,False,False,False,False,False,True,False,False,False,False,False,False
736,False,False,False,False,False,False,False,False,False,False,True,False,False
4383,False,False,False,False,False,False,False,False,False,False,False,True,False